// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapseDeleteController from "./collapse_delete_controller"
application.register("collapse-delete", CollapseDeleteController)

import CollapseHoursController from "./collapse_hours_controller"
application.register("collapse-hours", CollapseHoursController)

import DynamicMinutesController from "./dynamic_minutes_controller"
application.register("dynamic-minutes", DynamicMinutesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ProjectReportsController from "./project_reports_controller"
application.register("project-reports", ProjectReportsController)

import ReportEditController from "./report_edit_controller"
application.register("report-edit", ReportEditController)

import TimeTasksController from "./time_tasks_controller"
application.register("time-tasks", TimeTasksController)

import UserReportsBoxesController from "./user_reports_boxes_controller"
application.register("user-reports-boxes", UserReportsBoxesController)

import UserReportsController from "./user_reports_controller"
application.register("user-reports", UserReportsController)
