// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckBoxesController from "./check_boxes_controller"
application.register("check-boxes", CheckBoxesController)

import CollapseHoursController from "./collapse_hours_controller"
application.register("collapse-hours", CollapseHoursController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReportsController from "./reports_controller"
application.register("reports", ReportsController)
